# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :project do

    # checkout release branch
    #ensure_git_status_clean

    # clear data
    clear_derived_data
    xcclean(
        scheme: "GBShop",
        workspace: "GBShop.xcworkspace"
    )

    # update a dependencies
    cocoapods(
        use_bundle_exec: false
    )

    # run tests
    run_tests

    increment_build_number
    set_info_plist_value(path: "./GBShop/Supporting Files/Info.plist", key: "CFBundleShortVersionString", value: "2.0")


    # commit changes to git
    versionNumber = get_version_number
    buildNumber = get_build_number
    tag = "#{versionNumber}.#{buildNumber}"

  end
end

